workflows:
  android-release:
    name: SweetData VPN – Android Release
    max_build_duration: 60

    # ✅ MUST BE LINUX FOR WIREGUARD
    environment:
      os: linux
      java: 17

      groups:
        - Release_keystore

    scripts:
      - name: Make gradlew executable
        script: chmod +x gradlew

      - name: Set up local.properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties
          echo "ndk.dir=$ANDROID_NDK_ROOT" >> local.properties

      - name: Enable AndroidX
        script: |
          echo "android.useAndroidX=true" >> gradle.properties
          echo "android.enableJetifier=true" >> gradle.properties

      # ✅ Decode keystore safely
      - name: Decode keystore
        script: |
          mkdir -p $HOME/keystores
          echo "$KEYSTORE_BASE64" | base64 --decode > $HOME/keystores/release.jks
          ls -l $HOME/keystores

      # ✅ BUILD SIGNED APK
      - name: Build Release APK
        script: |
          ./gradlew assembleRelease \
            -Pandroid.injected.signing.store.file=$HOME/keystores/release.jks \
            -Pandroid.injected.signing.store.password=$KEYSTORE_PASSWORD \
            -Pandroid.injected.signing.key.alias=$KEY_ALIAS \
            -Pandroid.injected.signing.key.password=$KEY_PASSWORD

      # ✅ BUILD SIGNED AAB
      - name: Build Release AAB
        script: |
          ./gradlew bundleRelease \
            -Pandroid.injected.signing.store.file=$HOME/keystores/release.jks \
            -Pandroid.injected.signing.store.password=$KEYSTORE_PASSWORD \
            -Pandroid.injected.signing.key.alias=$KEY_ALIAS \
            -Pandroid.injected.signing.key.password=$KEY_PASSWORD

    artifacts:
      - app/build/outputs/**/*.apk
      - app/build/outputs/**/*.aab

    publishing:
      email:
        recipients:
          - kevinjah08@gmail.com
        notify:
          success: true
          failure: true
