workflows:
  android-wireguard:
    name: WireGuard Android Build
    max_build_duration: 60
    environment:
      vars:
        PACKAGE_NAME: "com.wireguard.android"
      android_signing:
        - keystore_reference
      groups:
        - google_play
      java: 17

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true

    scripts:
      - name: Set executable permission for Gradle
        script: chmod +x ./gradlew

      - name: Build Debug APK
        script: |
          ./gradlew :app:assembleDebug

    artifacts:
      - app/build/outputs/**/*.apk

    publishing:
      email:
        recipients:
          - jontemsee24@gmail.com@email.com
        notify:
          success: true
          failure: true
